USE BD_TAURUS;
GO

CREATE TABLE PERSONA (
    IDPERSONA INT IDENTITY(1,1) PRIMARY KEY,
    DNI VARCHAR(8) NULL UNIQUE,
    NOMBRES VARCHAR(100) NOT NULL,
    APELLIDO_PATERNO VARCHAR(100) NOT NULL,
    APELLIDO_MATERNO VARCHAR(100) NULL,
    CELULAR VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(100) NULL,
    DIRECCION VARCHAR(200) NULL,
    FECHA_REGISTRO DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    ESTADO BIT NOT NULL DEFAULT 1
);
GO

CREATE TABLE CLIENTE (
    IDCLIENTE INT IDENTITY(1,1) PRIMARY KEY,
    IDPERSONA INT NOT NULL UNIQUE,
    FECHA_REGISTRO DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    ESTADO BIT NOT NULL DEFAULT 1,

    CONSTRAINT FK_CLIENTE_PERSONA
        FOREIGN KEY (IDPERSONA)
        REFERENCES PERSONA(IDPERSONA)
);
GO

CREATE TABLE MARCA (
    IDMARCA INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL UNIQUE,
    ESTADO BIT NOT NULL DEFAULT 1
);
GO

CREATE TABLE MODELO (
    IDMODELO INT IDENTITY(1,1) PRIMARY KEY,
    IDMARCA INT NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    ESTADO BIT NOT NULL DEFAULT 1,

    CONSTRAINT FK_MODELO_MARCA
        FOREIGN KEY (IDMARCA)
        REFERENCES MARCA(IDMARCA),

    CONSTRAINT UQ_MODELO_MARCA
        UNIQUE (IDMARCA, NOMBRE)
);
GO

CREATE TABLE EQUIPO (
    IDEQUIPO INT IDENTITY(1,1) PRIMARY KEY,
    IDCLIENTE INT NOT NULL,
    IDMODELO INT NOT NULL,
    TIPO_DISPOSITIVO VARCHAR(30) NOT NULL DEFAULT 'Celular',
    IMEI VARCHAR(20) NULL,
    NUMERO_SERIE VARCHAR(50) NULL,
    COLOR VARCHAR(50) NULL,
    OBSERVACIONES VARCHAR(500) NULL,
    FECHA_REGISTRO DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    ESTADO BIT NOT NULL DEFAULT 1,

    CONSTRAINT FK_EQUIPO_CLIENTE
        FOREIGN KEY (IDCLIENTE)
        REFERENCES CLIENTE(IDCLIENTE),

    CONSTRAINT FK_EQUIPO_MODELO
        FOREIGN KEY (IDMODELO)
        REFERENCES MODELO(IDMODELO)
);
GO

CREATE TABLE ESTADO_REPARACION (
    IDESTADO INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL UNIQUE,
    ORDEN INT NOT NULL,
    ESTADO BIT NOT NULL DEFAULT 1
);
GO

CREATE TABLE REPARACION (
    IDREPARACION INT IDENTITY(1,1) PRIMARY KEY,
    CODIGO VARCHAR(30) NOT NULL UNIQUE,
    IDEQUIPO INT NOT NULL,
    IDTECNICO INT NULL,
    IDESTADO INT NOT NULL,

    FALLA_REPORTADA VARCHAR(1000) NOT NULL,
    DIAGNOSTICO VARCHAR(1000) NULL,
    SOLUCION VARCHAR(1000) NULL,

    COSTO_ESTIMADO DECIMAL(10,2) NULL,
    COSTO_FINAL DECIMAL(10,2) NULL,

    FECHA_INGRESO DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    FECHA_ESTIMADA DATETIME2 NULL,
    FECHA_ENTREGA DATETIME2 NULL,

    GARANTIA_DIAS INT NOT NULL DEFAULT 0,
    OBSERVACIONES VARCHAR(1000) NULL,

    ESTADO BIT NOT NULL DEFAULT 1,

    CONSTRAINT FK_REPARACION_EQUIPO
        FOREIGN KEY (IDEQUIPO)
        REFERENCES EQUIPO(IDEQUIPO),

    CONSTRAINT FK_REPARACION_ESTADO
        FOREIGN KEY (IDESTADO)
        REFERENCES ESTADO_REPARACION(IDESTADO)
);
GO

CREATE TABLE HISTORIAL_REPARACION (
    IDHISTORIAL INT IDENTITY(1,1) PRIMARY KEY,
    IDREPARACION INT NOT NULL,
    IDESTADO INT NOT NULL,
    IDUSUARIO INT NULL,
    COMENTARIO VARCHAR(500) NULL,
    FECHA DATETIME2 NOT NULL DEFAULT SYSDATETIME(),

    CONSTRAINT FK_HISTORIAL_REPARACION
        FOREIGN KEY (IDREPARACION)
        REFERENCES REPARACION(IDREPARACION),

    CONSTRAINT FK_HISTORIAL_ESTADO
        FOREIGN KEY (IDESTADO)
        REFERENCES ESTADO_REPARACION(IDESTADO)
);
GO
